#!/bin/bash

echo "🚀 Setting up GitHub repository for Online-Book-Store"
echo ""
echo "📋 Please run these commands (replace YOUR_USERNAME with your GitHub username):"
echo ""
echo "1. Remove the current remote (if any):"
echo "   git remote remove origin"
echo ""
echo "2. Add your GitHub repository:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/Online-Book-Store.git"
echo ""
echo "3. Push to GitHub:"
echo "   git push -u origin main"
echo ""
echo "📍 Example (replace 'johndoe' with your username):"
echo "   git remote add origin https://github.com/johndoe/Online-Book-Store.git"
echo "   git push -u origin main"
echo ""
echo "✅ After pushing, your Enhanced Bookstore will be live on GitHub!"
echo ""
echo "🎯 Next steps after GitHub setup:"
echo "   1. Deploy backend to Railway/Render"
echo "   2. Deploy frontend to Netlify/Vercel"
echo "   3. Configure environment variables"
echo "   4. Test the live application"